file = open("input.txt", "w")
file.write("My weekly assignment. " \
"\nA program that reads a txt file and writes to another txt file." \
"\nIt also converts it to uppercase.")
with open("input.txt", "r") as file: data = file.read()
num = len(data.split())
data = data.upper()
print(data)
print(num)
file = open("output.txt", "w")
file.write(data)
file = open("output.txt", "a")
file.write(f"\nThe number of words in the input file is: {num}")
print(f"Successfully appended to: 'output.txt'")
with open("output.txt", "r") as file: print(file.read())
file.close()